## Numpy Library for Scientific Computing

**Areas to Cover**
* Importing the module 1
* Basic Attributes of the Numpy lib 2
* Data types
* Indexing and Slicing 
* Basic Matrix Computations
* Arithmetic Operations
* Elementwise Functions
* Summary and Next steps

Before we start working with the numpy library, we need to first import the Numpy class known as the ndarray. To do this, we use the code below,

### Importing the module 

In [1]:
#importing the numpy class
import numpy as np                                     # np happens to be a conventional acronym for numpy.

Lets check out the built in functions

In [2]:
#help(np.ndarray)

### Basic Attributes of the Numpy lib 2

Next is to look into the basic attributes of numpy library. They include;
* shape
* ndim
* size
* nbytes
* dtype

Lets check them out in this following examples. First we have to create a numpy array.

In [3]:
first_data = np.array([[2, 3], [4,5]])              # This becomes our new array.

In [4]:
first_data                                          # Lets have a view of it.

array([[2, 3],
       [4, 5]])

In [5]:
#ndarray.shape
first_data.shape                                    # This is a tuple that gives the number rows & columns of an array

(2, 2)

In [6]:
#ndarray.ndim
first_data.ndim                                   # This outputs the number of dimensions (axes)

2

In [7]:
#ndarray.size
first_data.size                                   # This outputs the Number of elements in the array

4

In [8]:
#ndarray.nbytes
first_data.nbytes                                 # Outputs thetotal number of bytes required to store the array data

16

In [9]:
#ndarray.dtype
first_data.dtype                                  # Describes the format of the elements in the array.

dtype('int32')


### Numpy Data types

The numpy array supports varieties of data types. Although all elements must be of the same data type, hence if float, all elementsin the array must be float, if integers, all elements in tthe array must be integers etc. The table below gives a list of different data types supported by the numpy array, with their corresponding descriptions.

**Data types**                >>>>>>>>         **Descriptions**

* **bool_**                >>>>>>>>>Boolean (True or False) stored as a byte
* **int_**                >>>>>>>>>>Default integer type (same as C long; normally either int64 or int32)
* **intc**                >>>>>>>>>>>Identical to C int (normally int32 or int64)
* **intp**                 >>>>>>>>>>Integer used for indexing (same as C size_t; normally either int32 or int64)
* **int8**                 >>>>>>>>>>Byte (–128 to 127)
* **int16**                >>>>>>>>>Integer (–32768 to 32767)
* **int32**               >>>>>>>>>Integer (–2147483648 to 2147483647)
* **int64**                >>>>>>>>>Integer (–9223372036854775808 to 9223372036854775807)
* **uint8**                >>>>>>>>>Unsigned integer (0 to 255)
* **uint16**              >>>>>>>>Unsigned integer (0 to 65535)
* **uint32**               >>>>>>>>Unsigned integer (0 to 4294967295)
* **uint64**               >>>>>>>>Unsigned integer (0 to 18446744073709551615)
* **float_**               >>>>>>>>>Shorthand for float64
* **float16**              >>>>>>>>Half precision float: sign bit, 5-bit exponent, 10-bit mantissa
* **float32**              >>>>>>>>Single precision float: sign bit, 8-bit exponent, 23-bit mantissa
* **float64**              >>>>>>>>Double precision float: sign bit, 11-bit exponent, 52-bit mantissa
* **complex_**             >>>>>>Shorthand for complex128
* **complex64**            >>>>>Complex number, represented by two 32-bit floats (real and imaginary components)
* **complex128**           >>>>Complex number, represented by two 64-bit floats (real and imaginary components)

The following examples show how to define these various data types

In [10]:
sec_data = np.array([1, 2, 3], dtype=bool)         # Declares the all elements into boolen values

In [11]:
sec_data                                           # Outputs True all through, since our array elements are all greater than 0

array([ True,  True,  True])

In [12]:
sec_data = np.array([1, 2, 3], dtype=float)        # Declares the all elements into floating values

In [13]:
sec_data                                           # Outputs floating points

array([1., 2., 3.])

In [14]:
sec_data = np.array([1, 2, 3], dtype=complex)     # Considers all elements as complex numbers

In [15]:
sec_data                                         

array([1.+0.j, 2.+0.j, 3.+0.j])

###  Indexing and Slicing

During various kinds of computational and mathematical analysis, it might be necessary to locate some specific elements of an array. Or possibily to split the array into various parts or aggregates.

**Expression**    >>>>>>>> **Description**

* **a[m]**  >>>>>>>>>Select element at index m, where m is an integer (start counting form 0).
* **a[-m]** >>>>>>>>>Select the n th element from the end of the list, where n is an integer. The last element in the list is addressed as –1, the second to last element as –2, and so on.
* **a[m:n]** >>>>>>>>Select elements with index starting at m and ending at n − 1 (m and n are integers).

* **a[:] or a[0:-1]** >>>Select all elements in the given axis.
* **a[:n]** >>>>>>>>>>Select elements starting with index 0 and going up to index n − 1 (integer).
* **a[m:] or a[m:-1]** >Select elements starting with index m (integer) and going up to the last element inthe array.
* **a[m:n:p]** >>>>>>>Select elements with index m through n (exclusive), with increment p.
* **a[::-1]** >>>>>>>>>Select all the elements, in reverse order.

To illustrate how these actions above can be performed on an array, we will be using few examples to explain them. 

In [16]:
a = np.array([[2, 3, 4], [40, 50, 60], [11, 22, 33]])

In [17]:
a

array([[ 2,  3,  4],
       [40, 50, 60],
       [11, 22, 33]])

In [18]:
a[0]                                         #This outputs all all elements with index row 0.

array([2, 3, 4])

In [19]:
a[-1]                                        #Outputs the last row

array([11, 22, 33])

In [20]:
a[1:2]                                       #Ouputs rows starting from index 1 to index (2-1 = 1)

array([[40, 50, 60]])

In [21]:
a[::-1]                                     #Outputs enteries in reverse order

array([[11, 22, 33],
       [40, 50, 60],
       [ 2,  3,  4]])

### Basic Matrix Computations
Numpy library has many capabilities in dealing with matrix operations. Because Matrix's vast applications, we will be leaving advanced matrix operations for another tutorial in "Linear Algebra in Python". 

In [22]:
matrixA = np.array([[2,4,6],[10,12,14],[20,22,24]])

In [23]:
matrixA

array([[ 2,  4,  6],
       [10, 12, 14],
       [20, 22, 24]])

In [24]:
np.sum(matrixA)                                    #Outputs sum of all elements in the array

114

In [25]:
np.std(matrixA)                                    #Outputs standard deviation of matrixA

7.542472332656507

In [26]:
np.mean(matrixA)                                  #Outputs mean

12.666666666666666

In [27]:
np.var(matrixA)                                   #Outputs variance of matrixA

56.888888888888886

In [28]:
np.transpose(matrixA)                            #Outputs transpose of matrixA

array([[ 2, 10, 20],
       [ 4, 12, 22],
       [ 6, 14, 24]])

In [29]:
matrixB = np.array([[4,6,3],[5,3,2],[6,8,2]])

In [30]:
np.dot(matrixA,matrixB)                        #Outputs the dot product of Matrix A and B

array([[ 64,  72,  26],
       [184, 208,  82],
       [334, 378, 152]])

In [31]:
np.cross(matrixA,matrixB)                        #Outputs the cross product of Matrix A and B

array([[ -24,   18,   -4],
       [ -18,   50,  -30],
       [-148,  104,   28]])

### Arithmetic Operations

Different arithmetic operations can be carried out using numpy. Lets consider the following basic operations;

In [32]:
i = np.array([1,2,3]) 
j = np.array([4,5,6])

In [33]:
i * j                                        #multiplication

array([ 4, 10, 18])

In [34]:
i - j                                        #subtraction

array([-3, -3, -3])

In [35]:
i + j                                        #addition

array([5, 7, 9])

In [36]:
i / j                                        #division

array([0.25, 0.4 , 0.5 ])

In [37]:
i ** 2                                       # array i to the power of 2

array([1, 4, 9], dtype=int32)

### Elementwise Functions
In addition to the basic arithmetic operations, numpy provides some specialized functions otherwise called the elementwise functions. These functions can be used in scientific, computational and numerical analysis. Lets check out few examples below; 

In [38]:
np.sin(np.deg2rad(30))                       #outputs Sin(30) in degrees

0.49999999999999994

In [39]:
np.sqrt(25)                                 #outputs the square root 

5.0

In [ ]:
#np.cosh

In [ ]:
#np.exp

In [ ]:
#np.log

In [40]:
#np.arcos

### Summary and Next steps

So far, we have been able to see the basics and various applications of Numpy library. Our next steps will be to further learn and see more intermediate and advanced applications of this library. 
Below are two courses that will be covering Numpy's intermediate to advanced applications. 

1. Codebasics Numpy playlist: https://youtube.com/playlist?list=PLUcmakntVocWGSKXIsUn1J7Wm9ekpZ87G

2. Introduction to Numerical Computing with Numpy | Scipy 2019 Tutorial | Alex Chabot Leclerc: https://youtu.be/ZB7BZMhfPgk 
